### ISSUE TITLE
Theseus isn't correctly loading Forge mod's metadata

### ISSUE THREAD

**Issue by Norbiros** [modrinth/code#345]
### Describe the bug

I created my own mod, and set metadata in `META-INF/mods.toml`:
```toml
modLoader = "javafml"
loaderVersion = "[38,)"
license = "GPL-3.0"
logoFile = "logo.png"
authors = "Cyborgcabbage,Norbiros"

[[mods]]
modId = "emojitype"
version = "${version}"
displayName = "Emoji Type"
description='''
A mod that lets you type minecraft emojis easier!
'''
credits="Thanks to cyborgcabbage for original mod!"

[[dependencies.emojitype]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.emojitype]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
```
And when I open it in theseus, It doesn't display correct display name, authors, and version:
![Screenshot_from_2023-07-17_11-13-00](https://github.com/modrinth/theseus/assets/89837724/e831f6fe-43a5-4767-8199-b1a2194b6ca2)
I don't know why It doesn't work with my mod, but it works for example with Cloth Config. I was checking my `mods.toml` few times and I didn't find any mistakes. Also, I am using [Architectury](https://github.com/architectury/) for my mod, but Cloth Config also uses and It works. 

### Steps to reproduce

1. Create new minecraft mod using Architectury
2. Build forge mod
3. Add it to any Theseus forge profile

### Expected behavior

It should display correct metadata.

### Additional context

I don't know what makes this problem. I looked in Theseus's code for loading mod's meta and I think it is correct, but if i check builded jar I also can't find any errors.
